name: Github Action Test Risk Analysis
description: "Example Action built with Probot Github Action Test Risk Analysis"
branding:
  icon: "gift"
  color: orange
runs:
  using: "node12"
  main: "dist/index.js"
